name = "roguevalleyrecreation-daleyorganics"
main = "src/index.js"
compatibility_date = "2024-07-04"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Static assets configuration
[site]
bucket = "./"
entry-point = "workers-site"

# Routes configuration
routes = [
  { pattern = "roguevalleyrecreation-daleyorganics.mikeschlottig.dev/*", zone_name = "mikeschlottig.dev" }
]

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
