name = "roguevalleyrecreation-daleyorganics"
main = "src/index.js"
compatibility_date = "2024-07-04"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
